#!/usr/bin/env bun
import { promises as fs } from "node:fs";
import path from "node:path";

export interface CoreGuidelineRule {
  id: string;
  title: string;
  section: string;
  anchor: string;
  url: string;
  reason?: string;
  enforcement?: string;
  content: string;
}

const GUIDELINES_URL =
  "https://raw.githubusercontent.com/isocpp/CppCoreGuidelines/master/CppCoreGuidelines.md";

const OUTPUT_JSON = path.resolve(import.meta.dir, "../src/data/guidelines.json");
const OUTPUT_TS = path.resolve(import.meta.dir, "../src/data/guidelines.ts");

function extractSubSection(content: string, header: string): string | undefined {
  const pattern = new RegExp(`#####\\s+${header}\\s*\\n\\n([\\s\\S]*?)(?=\\n#####|$)`, "i");
  const match = content.match(pattern);
  return match?.[1]?.trim();
}

export async function syncGuidelines(): Promise<CoreGuidelineRule[]> {
  console.log(`Fetching C++ Core Guidelines from ${GUIDELINES_URL}...`);

  let text: string;
  try {
    const res = await fetch(GUIDELINES_URL, {
      headers: {
        "User-Agent": "cpp-mcp-sync/1.1.1 (+https://github.com/CHOCEK-RB/cpp-mcp)",
      },
      signal: AbortSignal.timeout(15_000),
    });

    if (!res.ok) {
      throw new Error(`HTTP ${res.status} ${res.statusText}`);
    }
    text = await res.text();
  } catch (err) {
    console.warn(
      `Could not fetch latest CppCoreGuidelines: ${err instanceof Error ? err.message : String(err)}. Checking for local cache...`,
    );
    try {
      const existing = await fs.readFile(OUTPUT_JSON, "utf-8");
      return JSON.parse(existing) as CoreGuidelineRule[];
    } catch {
      throw new Error("No cached guidelines found and network request failed.");
    }
  }

  const lines = text.split("\n");
  let currentSection = "General";
  const rules: CoreGuidelineRule[] = [];

  interface RuleInProgress {
    id: string;
    title: string;
    anchor: string;
    section: string;
    url: string;
    contentLines: string[];
  }

  let currentRule: RuleInProgress | null = null;

  function finalizeRule(rule: RuleInProgress) {
    const content = rule.contentLines.join("\n").trim();
    const reason = extractSubSection(content, "Reason");
    const enforcement = extractSubSection(content, "Enforcement");

    rules.push({
      id: rule.id,
      title: rule.title,
      section: rule.section,
      anchor: rule.anchor,
      url: rule.url,
      ...(reason ? { reason } : {}),
      ...(enforcement ? { enforcement } : {}),
      content,
    });
  }

  for (const line of lines) {
    // Track major section: # <a name="..."></a>Section
    if (line.startsWith("# ") && !line.startsWith("## ")) {
      const match = line.match(/^#\s+(?:<a\s+name="[^"]*"><\/a>)?(.*)$/);
      if (match?.[1]) {
        currentSection = match[1].trim();
      }
      continue;
    }

    // Rule header: ### <a name="..."></a>RuleId: Title
    const ruleMatch = line.match(
      /^###\s+(?:<a\s+name="([^"]*)"><\/a>)?\s*([A-Za-z0-9_.-]+):\s*(.+)$/,
    );
    if (ruleMatch?.[2] && ruleMatch[3]) {
      if (currentRule) {
        finalizeRule(currentRule);
      }

      const anchor = ruleMatch[1] ?? "";
      const id = ruleMatch[2].trim();
      const title = ruleMatch[3].trim();

      currentRule = {
        id,
        title,
        anchor,
        section: currentSection,
        url: anchor
          ? `https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#${anchor}`
          : "https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines",
        contentLines: [],
      };
      continue;
    }

    if (currentRule) {
      if (line.startsWith("# ") || line.startsWith("## ")) {
        finalizeRule(currentRule);
        currentRule = null;
        if (line.startsWith("# ") && !line.startsWith("## ")) {
          const match = line.match(/^#\s+(?:<a\s+name="[^"]*"><\/a>)?(.*)$/);
          if (match?.[1]) {
            currentSection = match[1].trim();
          }
        }
      } else {
        currentRule.contentLines.push(line);
      }
    }
  }

  if (currentRule) {
    finalizeRule(currentRule);
  }

  await fs.mkdir(path.dirname(OUTPUT_JSON), { recursive: true });
  await fs.writeFile(OUTPUT_JSON, JSON.stringify(rules, null, 2), "utf-8");

  const tsContent = `// Auto-generated by scripts/sync-guidelines.ts. Do not edit directly.
import rawGuidelines from "./guidelines.json" with { type: "json" };

export interface CoreGuidelineRule {
  id: string;
  title: string;
  section: string;
  anchor: string;
  url: string;
  reason?: string;
  enforcement?: string;
  content: string;
}

export const CPP_CORE_GUIDELINES: CoreGuidelineRule[] = rawGuidelines as CoreGuidelineRule[];

export const GUIDELINE_BY_ID = new Map<string, CoreGuidelineRule>(
  CPP_CORE_GUIDELINES.map((rule) => [rule.id.toUpperCase(), rule]),
);
`;

  await fs.writeFile(OUTPUT_TS, tsContent, "utf-8");

  console.log(`✓ Parsed and saved ${rules.length} C++ Core Guidelines to:`);
  console.log(`  - ${OUTPUT_JSON}`);
  console.log(`  - ${OUTPUT_TS}`);

  return rules;
}

const isDirect =
  typeof process !== "undefined" &&
  process.argv[1] &&
  process.argv[1].endsWith("sync-guidelines.ts");

if (isDirect) {
  syncGuidelines().catch((err) => {
    console.error("Failed to sync C++ Core Guidelines:", err);
    process.exit(1);
  });
}
