// Auto-generated by scripts/sync-guidelines.ts. Do not edit directly.
import rawGuidelines from "./guidelines.json" with { type: "json" };

export interface CoreGuidelineRule {
  id: string;
  title: string;
  section: string;
  anchor: string;
  url: string;
  reason?: string;
  enforcement?: string;
  content: string;
}

export const CPP_CORE_GUIDELINES: CoreGuidelineRule[] = rawGuidelines as CoreGuidelineRule[];

export const GUIDELINE_BY_ID = new Map<string, CoreGuidelineRule>(
  CPP_CORE_GUIDELINES.map((rule) => [rule.id.toUpperCase(), rule]),
);
