// src/tools/project-scaffold.ts
// Scaffold modern C++ projects with xmake/CMake, C++ standards, test frameworks, and tooling configs.

import { execFile } from "node:child_process";
import { existsSync, promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import { isExecutableAvailable } from "../project/xmake.js";
import { loadProjectPolicy, resolveStandard } from "./project-policy.js";

const execFileAsync = promisify(execFile);

export type BuildSystem = "xmake" | "cmake";
export type ProjectType = "executable" | "library" | "header-only" | "cxx-modules" | "qt" | "cuda";
export type CppStandard = "11" | "14" | "17" | "20" | "23" | "26";
export type TestFramework = "catch2" | "gtest" | "doctest" | "none";
export type PackageManager = "xrepo" | "vcpkg" | "conan" | "none";

export const VALID_BUILD_SYSTEMS: ReadonlySet<string> = new Set(["xmake", "cmake"]);
export const VALID_PROJECT_TYPES: ReadonlySet<string> = new Set([
  "executable",
  "library",
  "header-only",
  "cxx-modules",
  "qt",
  "cuda",
]);
export const VALID_CPP_STANDARDS: ReadonlySet<string> = new Set([
  "11",
  "14",
  "17",
  "20",
  "23",
  "26",
]);
export const VALID_TEST_FRAMEWORKS: ReadonlySet<string> = new Set([
  "catch2",
  "gtest",
  "doctest",
  "none",
]);
export const VALID_PACKAGE_MANAGERS: ReadonlySet<string> = new Set([
  "xrepo",
  "vcpkg",
  "conan",
  "none",
]);

export const CPP_RESERVED_KEYWORDS: ReadonlySet<string> = new Set([
  "alignas",
  "alignof",
  "and",
  "and_eq",
  "asm",
  "atomic_cancel",
  "atomic_commit",
  "atomic_noexcept",
  "auto",
  "bitand",
  "bitor",
  "bool",
  "break",
  "case",
  "catch",
  "char",
  "char8_t",
  "char16_t",
  "char32_t",
  "class",
  "compl",
  "concept",
  "const",
  "consteval",
  "constexpr",
  "constinit",
  "const_cast",
  "continue",
  "co_await",
  "co_return",
  "co_yield",
  "decltype",
  "default",
  "delete",
  "do",
  "double",
  "dynamic_cast",
  "else",
  "enum",
  "explicit",
  "export",
  "extern",
  "false",
  "float",
  "for",
  "friend",
  "goto",
  "if",
  "inline",
  "int",
  "long",
  "module",
  "mutable",
  "namespace",
  "new",
  "noexcept",
  "not",
  "not_eq",
  "nullptr",
  "operator",
  "or",
  "or_eq",
  "private",
  "protected",
  "public",
  "reflexpr",
  "register",
  "reinterpret_cast",
  "requires",
  "return",
  "short",
  "signed",
  "sizeof",
  "static",
  "static_assert",
  "static_cast",
  "struct",
  "switch",
  "synchronized",
  "template",
  "this",
  "thread_local",
  "throw",
  "true",
  "try",
  "typedef",
  "typeid",
  "typename",
  "union",
  "unsigned",
  "using",
  "virtual",
  "void",
  "volatile",
  "wchar_t",
  "while",
  "xor",
  "xor_eq",
]);

export interface ScaffoldProjectOptions {
  projectName: string;
  targetDir?: string;
  buildSystem?: BuildSystem;
  projectType?: ProjectType;
  cppStandard?: CppStandard;
  testFramework?: TestFramework;
  packageManager?: PackageManager;
  initClangTools?: boolean;
  initGit?: boolean;
  dryRun?: boolean;
  overwrite?: boolean;
}

export interface ScaffoldProjectResult {
  success: boolean;
  projectName: string;
  projectDir: string;
  buildSystem: BuildSystem;
  projectType: ProjectType;
  cppStandard: CppStandard;
  testFramework: TestFramework;
  packageManager: PackageManager;
  filesCreated: string[];
  files: Record<string, string>;
  nextSteps: string[];
  gitInitialized?: boolean;
  message?: string;
}

function sanitizeIdentifier(name: string): string {
  const sanitized = name.replace(/[^a-zA-Z0-9_]/g, "_");
  if (/^[0-9]/.test(sanitized) || CPP_RESERVED_KEYWORDS.has(sanitized.toLowerCase())) {
    return `_${sanitized}`;
  }
  return sanitized;
}

function generateXmakeConfig(
  projectName: string,
  identifier: string,
  projectType: ProjectType,
  cppStandard: CppStandard,
  testFramework: TestFramework,
  packageManager: PackageManager,
): string {
  const lines: string[] = [
    `-- xmake.lua for ${projectName}`,
    "-- Generated by cpp-mcp scaffold",
    'add_rules("mode.debug", "mode.release")',
    "",
    `set_languages("c++${cppStandard}")`,
    'set_warnings("all", "extra")',
    "",
  ];

  if (testFramework === "catch2") {
    lines.push('add_requires("catch2 3.x")');
  } else if (testFramework === "gtest") {
    lines.push('add_requires("gtest")');
  } else if (testFramework === "doctest") {
    lines.push('add_requires("doctest")');
  }

  if (packageManager === "vcpkg") {
    lines.push('-- Note: Add vcpkg dependencies using add_requires("vcpkg::<package>")');
  } else if (packageManager === "conan") {
    lines.push('-- Note: Add conan dependencies using add_requires("conan::<package>")');
  }

  lines.push("");

  switch (projectType) {
    case "executable":
      lines.push(
        `target("${projectName}")`,
        '    set_kind("binary")',
        '    add_files("src/*.cpp")',
        '    add_includedirs("include")',
      );
      break;
    case "library":
      lines.push(
        `target("${projectName}")`,
        '    set_kind("static")',
        '    add_files("src/*.cpp")',
        '    add_includedirs("include", {public = true})',
        `    add_headerfiles("include/(${identifier}/*.hpp)")`,
      );
      break;
    case "header-only":
      lines.push(
        `target("${projectName}")`,
        '    set_kind("headeronly")',
        '    add_includedirs("include", {public = true})',
        `    add_headerfiles("include/(${identifier}/*.hpp)")`,
      );
      break;
    case "cxx-modules":
      lines.push(
        `target("${projectName}")`,
        '    set_kind("binary")',
        '    add_files("src/*.mpp", "src/*.cpp")',
        '    add_includedirs("include")',
      );
      break;
    case "qt":
      lines.push(
        `target("${projectName}")`,
        '    add_rules("qt.widgetapp")',
        '    add_files("src/*.cpp")',
        '    add_frameworks("QtWidgets")',
      );
      break;
    case "cuda":
      lines.push(
        `target("${projectName}")`,
        '    add_rules("cuda")',
        '    add_files("src/*.cu", "src/*.cpp")',
        '    add_includedirs("include")',
      );
      break;
  }

  if (testFramework !== "none") {
    lines.push("");
    lines.push(`target("${projectName}_tests")`);
    lines.push('    set_kind("binary")');
    lines.push("    set_default(false)");
    lines.push('    add_files("tests/*.cpp")');

    if (projectType === "executable") {
      lines.push(`    add_files("src/${identifier}.cpp")`);
      lines.push('    add_includedirs("include")');
    } else if (projectType === "cxx-modules") {
      lines.push('    add_files("src/*.mpp")');
      lines.push('    add_includedirs("include")');
    } else if (projectType === "library" || projectType === "header-only") {
      lines.push(`    add_deps("${projectName}")`);
    } else {
      lines.push('    add_includedirs("include")');
    }

    const pkgName =
      testFramework === "catch2" ? "catch2" : testFramework === "gtest" ? "gtest" : "doctest";
    lines.push(`    add_packages("${pkgName}")`);
    lines.push('    add_tests("default")');
  }

  lines.push("");
  return lines.join("\n");
}

function generateCMakeConfig(
  projectName: string,
  identifier: string,
  projectType: ProjectType,
  cppStandard: CppStandard,
  testFramework: TestFramework,
  packageManager: PackageManager,
): string {
  const minCMakeVer = projectType === "cxx-modules" ? "3.28" : "3.25";
  const lines: string[] = [
    "# CMakeLists.txt",
    "# Generated by cpp-mcp scaffold",
    `cmake_minimum_required(VERSION ${minCMakeVer})`,
    `project(${projectName} VERSION 0.1.0 LANGUAGES CXX${projectType === "cuda" ? " CUDA" : ""})`,
    "",
    `set(CMAKE_CXX_STANDARD ${cppStandard})`,
    "set(CMAKE_CXX_STANDARD_REQUIRED ON)",
    "set(CMAKE_CXX_EXTENSIONS OFF)",
    "set(CMAKE_EXPORT_COMPILE_COMMANDS ON)",
    "",
    "if(MSVC)",
    "    add_compile_options(/W4 /permissive-)",
    "else()",
    "    add_compile_options(-Wall -Wextra -Wpedantic)",
    "endif()",
    "",
  ];

  if (packageManager === "vcpkg") {
    lines.push(
      "# Note: Run cmake with -DCMAKE_TOOLCHAIN_FILE=[vcpkg-root]/scripts/buildsystems/vcpkg.cmake",
    );
    lines.push("");
  }

  switch (projectType) {
    case "executable":
      lines.push(
        `add_executable(${projectName}`,
        "    src/main.cpp",
        `    src/${identifier}.cpp`,
        ")",
        `target_include_directories(${projectName} PRIVATE include)`,
      );
      break;
    case "library":
      lines.push(
        `add_library(${projectName} STATIC`,
        `    src/${identifier}.cpp`,
        ")",
        `target_include_directories(${projectName} PUBLIC`,
        // biome-ignore lint/suspicious/noTemplateCurlyInString: CMake generator expression syntax
        "    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>",
        "    $<INSTALL_INTERFACE:include>",
        ")",
      );
      break;
    case "header-only":
      lines.push(
        `add_library(${projectName} INTERFACE)`,
        `target_include_directories(${projectName} INTERFACE`,
        // biome-ignore lint/suspicious/noTemplateCurlyInString: CMake generator expression syntax
        "    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>",
        "    $<INSTALL_INTERFACE:include>",
        ")",
      );
      break;
    case "cxx-modules":
      lines.push(
        `add_executable(${projectName}`,
        "    src/main.cpp",
        ")",
        `target_sources(${projectName}`,
        "    PUBLIC",
        "        FILE_SET CXX_MODULES FILES",
        `        src/${identifier}.mpp`,
        ")",
      );
      break;
    case "qt":
      lines.push(
        "find_package(Qt6 REQUIRED COMPONENTS Widgets)",
        "qt_standard_project_setup()",
        `qt_add_executable(${projectName}`,
        "    src/main.cpp",
        "    src/mainwindow.cpp",
        "    src/mainwindow.hpp",
        ")",
        `target_link_libraries(${projectName} PRIVATE Qt6::Widgets)`,
      );
      break;
    case "cuda":
      lines.push(
        `add_executable(${projectName}`,
        "    src/main.cpp",
        "    src/kernel.cu",
        ")",
        `target_include_directories(${projectName} PRIVATE include)`,
        `set_target_properties(${projectName} PROPERTIES CUDA_SEPARABLE_COMPILATION ON)`,
      );
      break;
  }

  if (testFramework !== "none") {
    lines.push("");
    lines.push("enable_testing()");
    lines.push("include(FetchContent)");

    if (testFramework === "catch2") {
      lines.push(
        "FetchContent_Declare(",
        "    Catch2",
        "    GIT_REPOSITORY https://github.com/catchorg/Catch2.git",
        "    GIT_TAG v3.5.3",
        ")",
        "FetchContent_MakeAvailable(Catch2)",
        "",
        `add_executable(${projectName}_tests tests/test_main.cpp)`,
      );
      if (projectType === "executable") {
        lines.push(
          `target_sources(${projectName}_tests PRIVATE src/${identifier}.cpp)`,
          `target_include_directories(${projectName}_tests PRIVATE include)`,
        );
      } else if (projectType === "library" || projectType === "header-only") {
        lines.push(`target_link_libraries(${projectName}_tests PRIVATE ${projectName})`);
      }
      lines.push(
        `target_link_libraries(${projectName}_tests PRIVATE Catch2::Catch2WithMain)`,
        "include(CTest)",
        "include(Catch)",
        `catch_discover_tests(${projectName}_tests)`,
      );
    } else if (testFramework === "gtest") {
      lines.push(
        "FetchContent_Declare(",
        "    googletest",
        "    GIT_REPOSITORY https://github.com/google/googletest.git",
        "    GIT_TAG v1.14.0",
        ")",
        "FetchContent_MakeAvailable(googletest)",
        "",
        `add_executable(${projectName}_tests tests/test_main.cpp)`,
      );
      if (projectType === "executable") {
        lines.push(
          `target_sources(${projectName}_tests PRIVATE src/${identifier}.cpp)`,
          `target_include_directories(${projectName}_tests PRIVATE include)`,
        );
      } else if (projectType === "library" || projectType === "header-only") {
        lines.push(`target_link_libraries(${projectName}_tests PRIVATE ${projectName})`);
      }
      lines.push(
        `target_link_libraries(${projectName}_tests PRIVATE GTest::gtest_main)`,
        "include(GoogleTest)",
        `gtest_discover_tests(${projectName}_tests)`,
      );
    } else if (testFramework === "doctest") {
      lines.push(
        "FetchContent_Declare(",
        "    doctest",
        "    GIT_REPOSITORY https://github.com/doctest/doctest.git",
        "    GIT_TAG v2.4.11",
        ")",
        "FetchContent_MakeAvailable(doctest)",
        "",
        `add_executable(${projectName}_tests tests/test_main.cpp)`,
      );
      if (projectType === "executable") {
        lines.push(
          `target_sources(${projectName}_tests PRIVATE src/${identifier}.cpp)`,
          `target_include_directories(${projectName}_tests PRIVATE include)`,
        );
      } else if (projectType === "library" || projectType === "header-only") {
        lines.push(`target_link_libraries(${projectName}_tests PRIVATE ${projectName})`);
      }
      lines.push(
        `target_link_libraries(${projectName}_tests PRIVATE doctest::doctest)`,
        `add_test(NAME ${projectName}_tests COMMAND ${projectName}_tests)`,
      );
    }
  }

  lines.push("");
  return lines.join("\n");
}

function generateClangFormat(cppStandard: CppStandard): string {
  return [
    "# .clang-format",
    `# Google style preset configured for C++${cppStandard}`,
    "BasedOnStyle: Google",
    "Language: Cpp",
    `Standard: c++${cppStandard}`,
    "ColumnLimit: 100",
    "IndentWidth: 4",
    "TabWidth: 4",
    "UseTab: Never",
    "AccessModifierOffset: -4",
    "SortIncludes: CaseSensitive",
    "",
  ].join("\n");
}

function generateClangd(cppStandard: CppStandard): string {
  return [
    "# .clangd",
    "# Modern clangd configuration for intelligent LSP diagnostics and indexing",
    "CompileFlags:",
    "  Add:",
    `    - -std=c++${cppStandard}`,
    "    - -Wall",
    "    - -Wextra",
    "    - -Wpedantic",
    "    - -Iinclude",
    '  CompilationDatabase: "."',
    "",
    "Diagnostics:",
    "  UnusedIncludes: Strict",
    "  ClangTidy:",
    "    Add:",
    "      - modernize*",
    "      - bugprone*",
    "      - performance*",
    "      - readability*",
    "      - cert*",
    "    Remove:",
    "      - modernize-use-trailing-return-type",
    "",
    "Index:",
    "  Background: Build",
    "",
  ].join("\n");
}

function generateGitignore(): string {
  return [
    "# Build output & artifacts",
    "build/",
    ".build/",
    "bin/",
    "out/",
    "*.o",
    "*.obj",
    "*.so",
    "*.dylib",
    "*.dll",
    "*.exe",
    "*.a",
    "*.lib",
    "",
    "# Xmake & Xrepo",
    ".xmake/",
    ".xrepo/",
    "",
    "# CMake",
    "CMakeCache.txt",
    "CMakeFiles/",
    "cmake_install.cmake",
    "",
    "# Clangd, LSP & IDE cache",
    ".cache/",
    "compile_commands.json",
    ".vscode/",
    ".idea/",
    "*.swp",
    "*~",
    "",
  ].join("\n");
}

function generateReadme(
  projectName: string,
  buildSystem: BuildSystem,
  cppStandard: CppStandard,
  testFramework: TestFramework,
): string {
  const lines: string[] = [
    `# ${projectName}`,
    "",
    `Modern C++${cppStandard} project bootstrapped with [cpp-mcp](https://github.com/CHOCEK-RB/cpp-mcp).`,
    "",
    "## Quick Start",
    "",
  ];

  if (buildSystem === "xmake") {
    lines.push("### Build with Xmake", "```bash", "xmake", "xmake run", "```", "");
    if (testFramework !== "none") {
      lines.push("### Run Tests", "```bash", "xmake test", "```", "");
    }
    lines.push(
      "### Generate compile_commands.json for clangd",
      "```bash",
      "xmake project -k compile_commands",
      "```",
    );
  } else {
    lines.push(
      "### Build with CMake",
      "```bash",
      "cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
      "cmake --build build",
      "```",
      "",
    );
    if (testFramework !== "none") {
      lines.push(
        "### Run Tests",
        "```bash",
        "ctest --test-dir build --output-on-failure",
        "```",
        "",
      );
    }
    lines.push("### Setup clangd LSP", "```bash", "ln -sf build/compile_commands.json .", "```");
  }

  lines.push("");
  return lines.join("\n");
}

export async function scaffoldProject(
  options: ScaffoldProjectOptions,
): Promise<ScaffoldProjectResult> {
  const {
    projectName,
    targetDir: rawTargetDir,
    buildSystem = "xmake",
    projectType = "executable",
    cppStandard: rawCppStandard,
    testFramework = "catch2",
    packageManager = buildSystem === "xmake" ? "xrepo" : "none",
    initClangTools = true,
    initGit = false,
    dryRun = false,
    overwrite = false,
  } = options;

  // No explicit flag or CPP_MCP_STD: fall back to the project policy, then "20".
  const { policy } = await loadProjectPolicy(process.cwd());
  const cppStandard = (resolveStandard({ flag: rawCppStandard, policy }) ?? "20") as CppStandard;

  if (!VALID_BUILD_SYSTEMS.has(buildSystem)) {
    throw new Error(
      `Invalid build system '${buildSystem}'. Supported: ${Array.from(VALID_BUILD_SYSTEMS).join(", ")}.`,
    );
  }
  if (!VALID_PROJECT_TYPES.has(projectType)) {
    throw new Error(
      `Invalid project type '${projectType}'. Supported: ${Array.from(VALID_PROJECT_TYPES).join(", ")}.`,
    );
  }
  if (!VALID_CPP_STANDARDS.has(cppStandard)) {
    throw new Error(
      `Invalid C++ standard '${cppStandard}'. Supported: ${Array.from(VALID_CPP_STANDARDS).join(", ")}.`,
    );
  }
  if (!VALID_TEST_FRAMEWORKS.has(testFramework)) {
    throw new Error(
      `Invalid test framework '${testFramework}'. Supported: ${Array.from(VALID_TEST_FRAMEWORKS).join(", ")}.`,
    );
  }
  if (!VALID_PACKAGE_MANAGERS.has(packageManager)) {
    throw new Error(
      `Invalid package manager '${packageManager}'. Supported: ${Array.from(VALID_PACKAGE_MANAGERS).join(", ")}.`,
    );
  }

  if (!projectName?.trim()) {
    throw new Error("Project name cannot be empty.");
  }

  const trimmedName = projectName.trim();
  if (!/^[a-zA-Z0-9_\-.]+$/.test(trimmedName)) {
    throw new Error(
      `Invalid project name '${trimmedName}'. Project names may only contain alphanumeric characters, underscores, hyphens, and dots.`,
    );
  }

  const identifier = sanitizeIdentifier(trimmedName);
  const targetDir = rawTargetDir
    ? path.resolve(rawTargetDir)
    : path.resolve(process.cwd(), trimmedName);

  // Validate directory state if writing to disk
  if (!dryRun && existsSync(targetDir)) {
    const existingEntries = await fs.readdir(targetDir);
    if (existingEntries.length > 0 && !overwrite) {
      throw new Error(
        `Directory '${targetDir}' already exists and contains ${existingEntries.length} file(s). Use 'overwrite: true' (or '--force') to proceed.`,
      );
    }
  }

  const files: Record<string, string> = {};

  // 1. Build configuration
  if (buildSystem === "xmake") {
    files["xmake.lua"] = generateXmakeConfig(
      trimmedName,
      identifier,
      projectType,
      cppStandard,
      testFramework,
      packageManager,
    );
  } else {
    files["CMakeLists.txt"] = generateCMakeConfig(
      trimmedName,
      identifier,
      projectType,
      cppStandard,
      testFramework,
      packageManager,
    );
  }

  // 2. Package manager manifest if applicable
  if (packageManager === "vcpkg") {
    files["vcpkg.json"] = JSON.stringify(
      {
        $schema:
          "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
        name: trimmedName.toLowerCase().replace(/_/g, "-"),
        "version-string": "0.1.0",
        dependencies: ["fmt"],
      },
      null,
      2,
    );
  } else if (packageManager === "conan") {
    files["conanfile.txt"] = [
      "[requires]",
      "fmt/10.2.1",
      "",
      "[generators]",
      "CMakeDeps",
      "CMakeToolchain",
      "",
    ].join("\n");
  }

  // 3. Tooling configurations
  if (initClangTools) {
    files[".clang-format"] = generateClangFormat(cppStandard);
    files[".clangd"] = generateClangd(cppStandard);
  }
  files[".gitignore"] = generateGitignore();
  files["README.md"] = generateReadme(trimmedName, buildSystem, cppStandard, testFramework);

  // 4. Source & Header Files
  if (projectType === "cxx-modules") {
    files[`src/${identifier}.mpp`] = [
      "module;",
      "#include <string>",
      `export module ${identifier};`,
      "",
      `export namespace ${identifier} {`,
      "",
      "[[nodiscard]] inline std::string get_greeting() {",
      `    return "Hello from C++${cppStandard} module '${trimmedName}'!";`,
      "}",
      "",
      "[[nodiscard]] constexpr int add(int a, int b) noexcept {",
      "    return a + b;",
      "}",
      "",
      `} // namespace ${identifier}`,
      "",
    ].join("\n");

    files["src/main.cpp"] = [
      "#include <iostream>",
      `import ${identifier};`,
      "",
      "int main() {",
      `    std::cout << ${identifier}::get_greeting() << std::endl;`,
      `    std::cout << "2 + 3 = " << ${identifier}::add(2, 3) << std::endl;`,
      "    return 0;",
      "}",
      "",
    ].join("\n");
  } else if (projectType === "qt") {
    files["src/mainwindow.hpp"] = [
      "#pragma once",
      "",
      "#include <QMainWindow>",
      "",
      "class MainWindow : public QMainWindow {",
      "    Q_OBJECT",
      "",
      "public:",
      "    explicit MainWindow(QWidget *parent = nullptr);",
      "    ~MainWindow() override = default;",
      "};",
      "",
    ].join("\n");

    files["src/mainwindow.cpp"] = [
      '#include "mainwindow.hpp"',
      "#include <QLabel>",
      "",
      "MainWindow::MainWindow(QWidget *parent)",
      "    : QMainWindow(parent) {",
      `    setWindowTitle("${trimmedName}");`,
      "    resize(640, 480);",
      `    setCentralWidget(new QLabel("Welcome to ${trimmedName} (Qt Application)", this));`,
      "}",
      "",
    ].join("\n");

    files["src/main.cpp"] = [
      "#include <QApplication>",
      '#include "mainwindow.hpp"',
      "",
      "int main(int argc, char *argv[]) {",
      "    QApplication app(argc, argv);",
      "    MainWindow window;",
      "    window.show();",
      "    return app.exec();",
      "}",
      "",
    ].join("\n");
  } else if (projectType === "cuda") {
    files[`include/${identifier}/kernel.cuh`] = [
      "#pragma once",
      "",
      `namespace ${identifier} {`,
      "",
      "void run_vector_add(const float *a, const float *b, float *c, int n);",
      "",
      `} // namespace ${identifier}`,
      "",
    ].join("\n");

    files["src/kernel.cu"] = [
      `#include "${identifier}/kernel.cuh"`,
      "#include <cuda_runtime.h>",
      "",
      "__global__ void vector_add_kernel(const float *a, const float *b, float *c, int n) {",
      "    int idx = blockDim.x * blockIdx.x + threadIdx.x;",
      "    if (idx < n) {",
      "        c[idx] = a[idx] + b[idx];",
      "    }",
      "}",
      "",
      `namespace ${identifier} {`,
      "",
      "void run_vector_add(const float *a, const float *b, float *c, int n) {",
      "    float *d_a = nullptr;",
      "    float *d_b = nullptr;",
      "    float *d_c = nullptr;",
      "    size_t size = n * sizeof(float);",
      "    cudaMalloc(&d_a, size);",
      "    cudaMalloc(&d_b, size);",
      "    cudaMalloc(&d_c, size);",
      "",
      "    cudaMemcpy(d_a, a, size, cudaMemcpyHostToDevice);",
      "    cudaMemcpy(d_b, b, size, cudaMemcpyHostToDevice);",
      "",
      "    int threads = 256;",
      "    int blocks = (n + threads - 1) / threads;",
      "    vector_add_kernel<<<blocks, threads>>>(d_a, d_b, d_c, n);",
      "",
      "    cudaMemcpy(c, d_c, size, cudaMemcpyDeviceToHost);",
      "",
      "    cudaFree(d_a);",
      "    cudaFree(d_b);",
      "    cudaFree(d_c);",
      "}",
      "",
      `} // namespace ${identifier}`,
      "",
    ].join("\n");

    files["src/main.cpp"] = [
      `#include "${identifier}/kernel.cuh"`,
      "#include <iostream>",
      "#include <vector>",
      "",
      "int main() {",
      "    constexpr int N = 1024;",
      "    std::vector<float> a(N, 1.0f);",
      "    std::vector<float> b(N, 2.0f);",
      "    std::vector<float> c(N, 0.0f);",
      "",
      `    ${identifier}::run_vector_add(a.data(), b.data(), c.data(), N);`,
      `    std::cout << "CUDA kernel finished. c[0] = " << c[0] << ", c[N-1] = " << c[N - 1] << std::endl;`,
      "    return 0;",
      "}",
      "",
    ].join("\n");
  } else if (projectType === "header-only") {
    files[`include/${identifier}/${identifier}.hpp`] = [
      "#pragma once",
      "",
      "#include <string>",
      "",
      `namespace ${identifier} {`,
      "",
      "[[nodiscard]] inline std::string get_greeting() {",
      `    return "Hello from header-only '${trimmedName}'!";`,
      "}",
      "",
      "[[nodiscard]] constexpr int add(int a, int b) noexcept {",
      "    return a + b;",
      "}",
      "",
      `} // namespace ${identifier}`,
      "",
    ].join("\n");
  } else {
    // executable or library
    files[`include/${identifier}/${identifier}.hpp`] = [
      "#pragma once",
      "",
      "#include <string>",
      "",
      `namespace ${identifier} {`,
      "",
      "[[nodiscard]] std::string get_greeting();",
      "[[nodiscard]] int add(int a, int b) noexcept;",
      "",
      `} // namespace ${identifier}`,
      "",
    ].join("\n");

    files[`src/${identifier}.cpp`] = [
      `#include "${identifier}/${identifier}.hpp"`,
      "",
      `namespace ${identifier} {`,
      "",
      "std::string get_greeting() {",
      `    return "Hello from '${trimmedName}'!";`,
      "}",
      "",
      "int add(int a, int b) noexcept {",
      "    return a + b;",
      "}",
      "",
      `} // namespace ${identifier}`,
      "",
    ].join("\n");

    if (projectType === "executable") {
      files["src/main.cpp"] = [
        `#include "${identifier}/${identifier}.hpp"`,
        "#include <iostream>",
        "",
        "int main() {",
        `    std::cout << ${identifier}::get_greeting() << std::endl;`,
        `    std::cout << "2 + 3 = " << ${identifier}::add(2, 3) << std::endl;`,
        "    return 0;",
        "}",
        "",
      ].join("\n");
    }
  }

  // 5. Test Files
  if (testFramework !== "none") {
    const isModules = projectType === "cxx-modules";
    const headerInclude = isModules
      ? `import ${identifier};`
      : `#include "${identifier}/${identifier}.hpp"`;

    if (testFramework === "catch2") {
      files["tests/test_main.cpp"] = [
        "#include <catch2/catch_test_macros.hpp>",
        headerInclude,
        "",
        'TEST_CASE("Greeting function returns expected message", "[greeting]") {',
        `    REQUIRE(${identifier}::get_greeting().find("${trimmedName}") != std::string::npos);`,
        "}",
        "",
        'TEST_CASE("Add function calculates sum correctly", "[math]") {',
        `    REQUIRE(${identifier}::add(2, 3) == 5);`,
        `    REQUIRE(${identifier}::add(-1, 1) == 0);`,
        "}",
        "",
      ].join("\n");
    } else if (testFramework === "gtest") {
      files["tests/test_main.cpp"] = [
        "#include <gtest/gtest.h>",
        headerInclude,
        "",
        "TEST(ProjectTest, Greeting) {",
        `    EXPECT_NE(${identifier}::get_greeting().find("${trimmedName}"), std::string::npos);`,
        "}",
        "",
        "TEST(ProjectTest, Add) {",
        `    EXPECT_EQ(${identifier}::add(2, 3), 5);`,
        `    EXPECT_EQ(${identifier}::add(-1, 1), 0);`,
        "}",
        "",
      ].join("\n");
    } else if (testFramework === "doctest") {
      files["tests/test_main.cpp"] = [
        "#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN",
        "#include <doctest/doctest.h>",
        headerInclude,
        "",
        'TEST_CASE("Testing greeting function") {',
        `    CHECK(${identifier}::get_greeting().find("${trimmedName}") != std::string::npos);`,
        "}",
        "",
        'TEST_CASE("Testing math add") {',
        `    CHECK(${identifier}::add(2, 3) == 5);`,
        `    CHECK(${identifier}::add(-1, 1) == 0);`,
        "}",
        "",
      ].join("\n");
    }
  }

  // 6. Write files to disk if not dryRun
  const filePaths = Object.keys(files);
  if (!dryRun) {
    await fs.mkdir(targetDir, { recursive: true });

    for (const relPath of filePaths) {
      const fullPath = path.join(targetDir, relPath);
      await fs.mkdir(path.dirname(fullPath), { recursive: true });
      await fs.writeFile(fullPath, files[relPath] ?? "", "utf-8");
    }
  }

  // 7. Optional Git init
  let gitInitialized = false;
  if (!dryRun && initGit) {
    const hasGit = await isExecutableAvailable("git");
    if (hasGit) {
      try {
        await execFileAsync("git", ["init"], { cwd: targetDir });
        gitInitialized = true;
      } catch {
        gitInitialized = false;
      }
    }
  }

  // 8. Next steps recommendations
  const nextSteps: string[] = [`cd ${path.relative(process.cwd(), targetDir) || "."}`];
  if (buildSystem === "xmake") {
    nextSteps.push("xmake");
    if (projectType === "executable" || projectType === "cxx-modules" || projectType === "cuda") {
      nextSteps.push("xmake run");
    }
    if (testFramework !== "none") {
      nextSteps.push("xmake test");
    }
    nextSteps.push("xmake project -k compile_commands");
  } else {
    nextSteps.push("cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON");
    nextSteps.push("cmake --build build");
    if (testFramework !== "none") {
      nextSteps.push("ctest --test-dir build --output-on-failure");
    }
  }

  return {
    success: true,
    projectName: trimmedName,
    projectDir: targetDir,
    buildSystem,
    projectType,
    cppStandard,
    testFramework,
    packageManager,
    filesCreated: filePaths,
    files,
    nextSteps,
    gitInitialized: initGit ? gitInitialized : undefined,
    message: dryRun
      ? `Dry-run preview for C++ project '${trimmedName}' with ${filePaths.length} file(s).`
      : `Successfully scaffolded C++ project '${trimmedName}' at '${targetDir}'.`,
  };
}
